### ISSUE TITLE
Update Fish360 Journal URL on Android App

### ISSUE THREAD

**Issue by Fish360** [Fish360/Journal#12]

**Comment by Fish360** [comment]
@yashsnehalshah,

You will need to use the Fish360 Android Dev Account.

Contact @jannunzi or myself directly.

**Comment by yashsnehalshah** [comment]
Hi Julio @Fish360,

Can you please give me access of Fish360 Android Dev Account and enlighten me a bit further on which URL i will have to change with which one? 

Thanks.

**Comment by Fish360** [comment]
@yashsnehalshah,

Email me at: JulioSilva@Fish360.Net.  I will send you the Fish360 Android Dev Account information.

@jannunzi,

Can you provide the URL information?

**Comment by yashsnehalshah** [comment]
Done @Fish360

**Comment by yashsnehalshah** [comment]
Hi @Fish360  and @jannunzi ,

This is my understanding of the task that i have to perform for sprint 1. This is my preliminary understanding(and I don't have previous Android experience), so please correct me if i am wrong.

1)Get the APK of the app from the play console.
2)Unpack the APK using Android Studio 3+(Not all files are unzipped, like java files)
3)Make the required changes
4)Build the APK again

Is this workflow correct? Please guide. 

Thanks.

**Comment by yashsnehalshah** [comment]
While I am going through the Android basics, i understand that the URL might be called from MainActivity.java and this is where changes might have to be made as this is the error i get when i open the app on my cellphone:
![screenfish360](https://user-images.githubusercontent.com/22141408/35840551-0f085b92-0ac5-11e8-9308-53a91db5bfca.png)

Please correct me i am am mistaken.

Thanks.

**Comment by yashsnehalshah** [comment]
I got some guidance from Professor on how to go ahead. Will do as per.

Thanks.

**Comment by yashsnehalshah** [comment]
Hi @Fish360 @jannunzi 

When i try to publish the new APK on google play, i get the following message:

![image](https://user-images.githubusercontent.com/22141408/36330390-6f505624-1337-11e8-8996-0c2c95e28e30.png)

Can someone please enlighten me on how can i have the correct signature on the APK?

Thanks.

**Comment by yashsnehalshah** [comment]
@jannunzi @Fish360  

Professor, as an update to this issue, I have found that the app inventor signs the apk (during export) with a certificate associated with a specific account. Since the previous apk was built using your app inventor account, it had that certificate. Thus, the sign was different when i built the apk from my account. I think there are two ways the issue can be resolved:

1) We build the apk again using your app inventor account(the signing will be internally performed by app inventor engine)

2) We can export a keystore from your account and then i can import it to mine and then have the engine sign the app with that keystore.

Please let me know which method seems more feasible to you.

Thanks

**Comment by Fish360** [comment]
#### 01-MAR-2018 Meeting Minutes

* Need to resolve the singing issue.

@jannunzi

**Comment by yashsnehalshah** [comment]
@Fish360 

Hi Julio,

Solved the problem and updated the app on Play Store. Please review.

Thanks.

**Comment by yashsnehalshah** [comment]
@Fish360 

Hi Julio,

Can you please allocate new issues/bugs to me?

**Comment by Fish360** [comment]
@yashsnehalshah 

See Spot Groups #40.  :-)

**Comment by yashsnehalshah** [comment]
@Fish360 

Yes Julio, will start working on it. Thanks.

**Comment by Fish360** [comment]
Tested and confirmed fix on my Android tablet.
Closing.

@yashsnehalshah
